server:
  port: 8080

spring:
  rsocket:
    server:
      mapping-path: /ws/
      transport: websocket

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
