apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rsocket-app-example
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: ghcr.io/thomasvitale/rsocket-app-example:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
            periodSeconds: 10
          resources:
            requests:
              memory: 512Mi
              cpu: "0.1"
            limits:
              memory: 512Mi
              cpu: "2"
